export const LOG_IN = 'LOG_IN '
export const SIGN_OUT = 'SIGN_OUT'
export const ACTIVE_LOGIN_PAGE = 'ACTICE_LOGIN_PAGE'
export const GET_USER_INFO = 'GET_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
